### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by kubusseekk** [Kemt66/FIMSGP15-patch22#1]
Po włączeniu gry modele zawodników dalej są z 2015 roku

**Comment by Kemt66** [comment]
> Po włączeniu gry modele zawodników dalej są z 2015 roku

Cześć, aby patch funkcjonował poprawnie, musisz ustawić jakość tekstur na najwyższą.
Daj znać czy udało się rozwiązać problem.

**Comment by kubusseekk** [comment]
Sorki, że dopiero teraz odpisuje, wszystko działa jak powinno, dziękuje bardzo :)
